### ISSUE TITLE
M2 - Create Sequence Diagram for important use case

### ISSUE THREAD

**Issue by nicholastwh** [ICT2201-p7-7/ICT2201_P7-7#31]

**Comment by nicholastwh** [comment]
[19 Oct] started first draft

**Comment by nicholastwh** [comment]
as per prof discussions on 20 Oct, just need sequence diagram for critical use cases (e.g. allocate job, submit availability)

**Comment by nicholastwh** [comment]
use cases identified as:
1. allocate job
2. submit availability
3. view job assignment

**Comment by nicholastwh** [comment]
[28 oct] sequence diagram for submit availability use case completed

**Comment by regleyat** [comment]
29th October, all sequence diagram completed and added to report
